/**
 * lib/video-download/launcher.ts — reading libi's yt-dlp launcher and judging
 * it runnable from the files alone (no spawn). The shapes are exactly what
 * `DependencyManager.installYtDlpViaUv` writes; the end-to-end install and
 * repair live in __tests__/unit/mcp/registry/yt-dlp-launcher-heal.test.ts.
 */
import path from "node:path";
import { describe, it, expect } from "vitest";
import {
  parseYtDlpLauncherTarget,
  parseEntryInterpreter,
  checkYtDlpLauncher,
  ytDlpLauncherPath,
} from "@/lib/video-download/launcher";

const UNIX_LAUNCHER =
  `#!/bin/bash\n# Generated by libi DependencyManager.installYtDlpViaUv\n` +
  `export SSL_CERT_FILE="/h/.libi/uv/tools/yt-dlp/lib/python3.12/site-packages/certifi/cacert.pem"\n` +
  `for _a in "$@"; do case "$_a" in *playlist*) exec "/h/.libi/uv/tools/yt-dlp/bin/yt-dlp" "$@";; esac; done\n` +
  `exec "/h/.libi/uv/tools/yt-dlp/bin/yt-dlp" --no-playlist "$@"\n`;

const CMD_SHIM =
  `@echo off\r\nset SSL_CERT_FILE=C:\\u\\cacert.pem\r\n` +
  `echo %*| findstr /I /C:"playlist" >nul\r\nif errorlevel 1 (\r\n` +
  `  "C:\\Users\\u\\.libi\\uv\\tools\\yt-dlp\\Scripts\\yt-dlp.exe" --no-playlist %*\r\n) else (\r\n` +
  `  "C:\\Users\\u\\.libi\\uv\\tools\\yt-dlp\\Scripts\\yt-dlp.exe" %*\r\n)\r\n`;

describe("parseYtDlpLauncherTarget", () => {
  it("reads the exec target out of the Unix wrapper libi writes", () => {
    expect(parseYtDlpLauncherTarget(UNIX_LAUNCHER)).toBe("/h/.libi/uv/tools/yt-dlp/bin/yt-dlp");
  });
  it("reads the quoted target out of the Windows .cmd shim libi writes", () => {
    expect(parseYtDlpLauncherTarget(CMD_SHIM)).toBe(
      "C:\\Users\\u\\.libi\\uv\\tools\\yt-dlp\\Scripts\\yt-dlp.exe",
    );
  });
  it("returns null for a file libi did not write", () => {
    expect(parseYtDlpLauncherTarget(`#!/bin/bash\nexec yt-dlp "$@"\n`)).toBeNull();
    expect(parseYtDlpLauncherTarget("")).toBeNull();
  });
});

describe("parseEntryInterpreter", () => {
  it("reads uv's direct shebang", () => {
    expect(parseEntryInterpreter("#!/h/.libi/uv/tools/yt-dlp/bin/python3\nimport sys\n")).toBe(
      "/h/.libi/uv/tools/yt-dlp/bin/python3",
    );
  });
  it("reads uv's /bin/sh trampoline for spaced paths — the SINGLE-quoted shape uv actually writes", () => {
    // Verbatim shape from `uv tool install` (uv 0.11.32) into a tool dir under
    // ".../Application Support/...", the packaged macOS home.
    expect(
      parseEntryInterpreter(
        `#!/bin/sh\n'''exec' '/Users/u/Library/Application Support/Libi/uv/tools/yt-dlp/bin/python' "$0" "$@"\n' '''\n`,
      ),
    ).toBe("/Users/u/Library/Application Support/Libi/uv/tools/yt-dlp/bin/python");
  });
  it("also accepts a double-quoted trampoline", () => {
    expect(
      parseEntryInterpreter(`#!/bin/sh\n'''exec' "/Users/a b/.libi/uv/tools/yt-dlp/bin/python3" "$0" "$@"\n' '''\n`),
    ).toBe("/Users/a b/.libi/uv/tools/yt-dlp/bin/python3");
  });
  // F5 (final review). uv shell-quotes the interpreter path, so a `'` in it is written as
  // `'"'"'`. This head is uv 0.11.32's real output for a venv under "o'brien home", captured
  // 2026-09-25 (`uv venv` + `uv pip install wheel`, then the first bytes of bin/wheel).
  const OBRIEN_TRAMPOLINE =
    `#!/bin/sh\n'''exec' '/Users/o'"'"'brien home/.libi/uv/tools/yt-dlp/bin/python' "$0" "$@"\n' '''\n` +
    `# -*- coding: utf-8 -*-\nimport sys\n`;

  it("undoes uv's '\"'\"' escape for a path containing a single quote (the real o'brien shape)", () => {
    expect(parseEntryInterpreter(OBRIEN_TRAMPOLINE)).toBe("/Users/o'brien home/.libi/uv/tools/yt-dlp/bin/python");
  });
  it("undoes the '\\'' escape too", () => {
    expect(
      parseEntryInterpreter(`#!/bin/sh\n'''exec' '/Users/o'\\''brien home/bin/python' "$0" "$@"\n' '''\n`),
    ).toBe("/Users/o'brien home/bin/python");
  });
  it("returns null — nothing to check — when the trampoline cannot be parsed unambiguously", () => {
    // unterminated quote; unquoted shell syntax; a relative result; no separator before "$0"
    expect(parseEntryInterpreter(`#!/bin/sh\n'''exec' '/Users/a b/bin/python "$0" "$@"\n`)).toBeNull();
    expect(parseEntryInterpreter(`#!/bin/sh\n'''exec' $HOME/bin/python "$0" "$@"\n`)).toBeNull();
    expect(parseEntryInterpreter(`#!/bin/sh\n'''exec' 'bin/python' "$0" "$@"\n`)).toBeNull();
    expect(parseEntryInterpreter(`#!/bin/sh\n'''exec' '/a/bin/python'"$0" "$@"\n`)).toBeNull();
  });
  it.skipIf(process.platform === "win32")("a present interpreter under an o'brien path is ok, never interpreter_missing", () => {
    const python = "/Users/o'brien home/.libi/uv/tools/yt-dlp/bin/python";
    const target = "/Users/o'brien home/.libi/uv/tools/yt-dlp/bin/yt-dlp";
    const launcher = `#!/bin/bash\nexec "${target}" --no-playlist "$@"\n`;
    const health = checkYtDlpLauncher({
      readFile: () => launcher,
      exists: (p) => p === target || p === python,
      readHead: () => OBRIEN_TRAMPOLINE,
    });
    expect(health).toMatchObject({ ok: true, target });
  });
  it("has nothing to check for env shebangs, /bin/sh scripts and binaries", () => {
    expect(parseEntryInterpreter("#!/usr/bin/env python3\n")).toBeNull();
    expect(parseEntryInterpreter("#!/bin/sh\necho hi\n")).toBeNull();
    expect(parseEntryInterpreter("\u0000MZ\u0090")).toBeNull();
  });
});

describe("checkYtDlpLauncher", () => {
  const io = (files: Record<string, string>, present: string[]) => ({
    readFile: (p: string) => {
      const hit = Object.entries(files).find(([k]) => p.endsWith(k));
      if (!hit) throw Object.assign(new Error("ENOENT"), { code: "ENOENT" });
      return hit[1];
    },
    exists: (p: string) => present.includes(p),
    readHead: (p: string) => (p.endsWith("bin/yt-dlp") ? "#!/h/.libi/uv/tools/yt-dlp/bin/python3\n" : ""),
  });

  it("missing — no launcher (the first-use install)", () => {
    expect(checkYtDlpLauncher(io({}, []))).toMatchObject({ ok: false, reason: "missing" });
  });
  // The launcher's own file name: `yt-dlp`, or `yt-dlp.cmd` on Windows.
  const LAUNCHER = path.basename(ytDlpLauncherPath());

  it("unrecognised — no target libi could have written", () => {
    expect(checkYtDlpLauncher(io({ [LAUNCHER]: `exec yt-dlp "$@"` }, []))).toMatchObject({
      ok: false,
      reason: "unrecognised",
    });
  });
  it.skipIf(process.platform === "win32")("target_missing — the entry point it execs is gone", () => {
    expect(checkYtDlpLauncher(io({ "yt-dlp": UNIX_LAUNCHER }, []))).toMatchObject({
      ok: false,
      reason: "target_missing",
      target: "/h/.libi/uv/tools/yt-dlp/bin/yt-dlp",
    });
  });
  // Windows reads the .cmd shim libi writes there, and has no interpreter check (the entry is an .exe).
  it.runIf(process.platform === "win32")("Windows: target_missing, then ok, for the .cmd shim's target", () => {
    const target = "C:\\Users\\u\\.libi\\uv\\tools\\yt-dlp\\Scripts\\yt-dlp.exe";
    expect(checkYtDlpLauncher(io({ [LAUNCHER]: CMD_SHIM }, []))).toMatchObject({ ok: false, reason: "target_missing", target });
    expect(checkYtDlpLauncher(io({ [LAUNCHER]: CMD_SHIM }, [target]))).toMatchObject({ ok: true, target });
  });
  it.skipIf(process.platform === "win32")("interpreter_missing — the entry exists but its Python does not", () => {
    expect(
      checkYtDlpLauncher(io({ "yt-dlp": UNIX_LAUNCHER }, ["/h/.libi/uv/tools/yt-dlp/bin/yt-dlp"])),
    ).toMatchObject({ ok: false, reason: "interpreter_missing" });
  });
  it.skipIf(process.platform === "win32")("ok — entry and interpreter both present", () => {
    expect(
      checkYtDlpLauncher(
        io({ "yt-dlp": UNIX_LAUNCHER }, [
          "/h/.libi/uv/tools/yt-dlp/bin/yt-dlp",
          "/h/.libi/uv/tools/yt-dlp/bin/python3",
        ]),
      ),
    ).toMatchObject({ ok: true, target: "/h/.libi/uv/tools/yt-dlp/bin/yt-dlp" });
  });
});
