import type { InferSelectModel, InferInsertModel } from "drizzle-orm";
import type { pieces, files, settings, mcpServers, skills, analysisSteps, analysisKeyframes, analysisAudioChunks, characters, items, characterAssets, itemAssets, tracks, jobs, assetFolders, folders, modelSchemas } from "./sqlite";

export type Piece = InferSelectModel<typeof pieces>;
export type NewPiece = InferInsertModel<typeof pieces>;
export type FileRecord = InferSelectModel<typeof files>;
export type NewFileRecord = InferInsertModel<typeof files>;
export type Setting = InferSelectModel<typeof settings>;
export type NewSetting = InferInsertModel<typeof settings>;
export type McpServerRecord = InferSelectModel<typeof mcpServers>;
export type NewMcpServerRecord = InferInsertModel<typeof mcpServers>;
export type Skill = InferSelectModel<typeof skills>;
export type NewSkill = InferInsertModel<typeof skills>;
export type AnalysisStepRow = InferSelectModel<typeof analysisSteps>;
export type NewAnalysisStepRow = InferInsertModel<typeof analysisSteps>;
export type AnalysisKeyframeRow = InferSelectModel<typeof analysisKeyframes>;
export type NewAnalysisKeyframeRow = InferInsertModel<typeof analysisKeyframes>;
export type AnalysisAudioChunkRow = InferSelectModel<typeof analysisAudioChunks>;
export type NewAnalysisAudioChunkRow = InferInsertModel<typeof analysisAudioChunks>;
export type CharacterRecord = typeof characters.$inferSelect;
export type ItemRecord = typeof items.$inferSelect;
export type CharacterAssetRecord = typeof characterAssets.$inferSelect;
export type ItemAssetRecord = typeof itemAssets.$inferSelect;
export type TrackRow = typeof tracks.$inferSelect;
export type JobRecord = typeof jobs.$inferSelect;
export type JobInsert = typeof jobs.$inferInsert;
export type AssetFolderRecord = typeof assetFolders.$inferSelect;
export type FolderRecord = typeof folders.$inferSelect;
export type ModelSchemaRow = typeof modelSchemas.$inferSelect;
export type NewModelSchemaRow = typeof modelSchemas.$inferInsert;
