/**
 * A parser for Python's `repr` of a JSON-ish value.
 *
 * Why libi owns one at all: Zernio's MCP is generated by fastmcp, whose tools
 * declare `outputSchema: { result: string }` with `x-fastmcp-wrap-result`
 * (verified live, 2026-09-20). The value inside that `result` string is the
 * server's Python object printed with `str()` / `repr()`, so it uses single
 * quotes and `None` / `True` / `False` — which `JSON.parse` rejects outright.
 * Without this, every Zernio answer parses to nothing and the adapter
 * normalizes a blank entity from it, silently.
 *
 * It is a real TOKENIZER, not a regex that swaps quotes and keywords. A
 * caption is user text: it contains apostrophes (`it's`), double quotes,
 * newlines, em dashes and emoji, and Python's `repr` switches the quote style
 * per string (`"it's"` when the value holds a `'`), so a substitution pass
 * corrupts exactly the payloads that matter most.
 *
 * Scope is deliberately narrow — dicts, lists, tuples, sets, strings, numbers,
 * `None` / `True` / `False` / `inf` / `nan`. Anything else (a constructor call
 * such as `datetime.datetime(...)`, a complex literal) THROWS rather than
 * being guessed at: a loud failure at the seam beats a plausible-looking wrong
 * value flowing into a post.
 */

/** A source string this parser could not read. Callers map it to a `SocialError`. */
export class PythonLiteralError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PythonLiteralError";
  }
}

/** Deep enough for any payload Zernio sends; a guard against a pathological input. */
const MAX_DEPTH = 64;

const DIGITS = /[0-9]/;
const IDENT_START = /[A-Za-z_]/;
const IDENT_CHAR = /[A-Za-z0-9_.]/;
/** Python's string prefixes. `b'…'` is decoded as text; `r'…'` keeps its escapes. */
const STRING_PREFIX = /^[bBrRuUfF]{1,2}(?=['"])/;

const SIMPLE_ESCAPES: Record<string, string> = {
  n: "\n", t: "\t", r: "\r", "\\": "\\", "'": "'", '"': '"',
  a: "\x07", b: "\b", f: "\f", v: "\v", "0": "\0",
};

/**
 * Parse one Python literal. Throws `PythonLiteralError` for anything this
 * grammar does not cover, including trailing characters after the value —
 * a half-read payload is not a payload.
 */
export function parsePythonLiteral(src: string): unknown {
  const p = new LiteralReader(src);
  const value = p.value(0);
  p.skipWhitespace();
  if (!p.atEnd()) p.fail("unexpected trailing characters");
  return value;
}

class LiteralReader {
  private pos = 0;
  constructor(private readonly src: string) {}

  atEnd(): boolean {
    return this.pos >= this.src.length;
  }

  fail(what: string): never {
    // Never the source text itself: a payload can carry a caption, and this
    // message may be logged or shown. Position only.
    throw new PythonLiteralError(`${what} at offset ${this.pos}`);
  }

  skipWhitespace(): void {
    while (this.pos < this.src.length && /\s/.test(this.src[this.pos])) this.pos++;
  }

  private peek(): string | undefined {
    return this.src[this.pos];
  }

  private expect(ch: string): void {
    if (this.src[this.pos] !== ch) this.fail(`expected "${ch}"`);
    this.pos++;
  }

  value(depth: number): unknown {
    if (depth > MAX_DEPTH) this.fail("nested too deeply");
    this.skipWhitespace();
    const ch = this.peek();
    if (ch === undefined) this.fail("unexpected end of input");
    if (ch === "{") return this.braced(depth);
    if (ch === "[") return this.sequence("[", "]", depth);
    if (ch === "(") return this.sequence("(", ")", depth);
    if (ch === "'" || ch === '"' || STRING_PREFIX.test(this.src.slice(this.pos))) return this.string();
    if (ch === "-" || ch === "+" || ch === "." || DIGITS.test(ch)) return this.number();
    if (IDENT_START.test(ch)) return this.keyword();
    this.fail("unexpected character");
  }

  /** `{}` / `{'k': v, …}` (dict) or `{v, …}` (set → array). */
  private braced(depth: number): unknown {
    this.expect("{");
    this.skipWhitespace();
    if (this.peek() === "}") {
      this.pos++;
      // `{}` is an empty DICT in Python; an empty set has no literal.
      return {};
    }
    const first = this.value(depth + 1);
    this.skipWhitespace();
    if (this.peek() === ":") {
      this.pos++;
      const out: Record<string, unknown> = { [keyOf(first, this)]: this.value(depth + 1) };
      while (true) {
        this.skipWhitespace();
        if (this.peek() === "}") { this.pos++; return out; }
        this.expect(",");
        this.skipWhitespace();
        if (this.peek() === "}") { this.pos++; return out; }
        const k = this.value(depth + 1);
        this.skipWhitespace();
        this.expect(":");
        out[keyOf(k, this)] = this.value(depth + 1);
      }
    }
    // A set. Python never reprs one as JSON data, but reading it as an array
    // beats failing on a payload that is otherwise fine.
    const items: unknown[] = [first];
    while (true) {
      this.skipWhitespace();
      if (this.peek() === "}") { this.pos++; return items; }
      this.expect(",");
      this.skipWhitespace();
      if (this.peek() === "}") { this.pos++; return items; }
      items.push(this.value(depth + 1));
    }
  }

  /** A list or a tuple; both become an array. */
  private sequence(open: string, close: string, depth: number): unknown[] {
    this.expect(open);
    const items: unknown[] = [];
    while (true) {
      this.skipWhitespace();
      if (this.peek() === close) { this.pos++; return items; }
      items.push(this.value(depth + 1));
      this.skipWhitespace();
      if (this.peek() === close) { this.pos++; return items; }
      this.expect(",");
    }
  }

  /**
   * A quoted string, in either quote style, optionally triple-quoted and
   * optionally prefixed. Every character between the quotes is taken
   * literally except an escape — which is what makes a caption containing
   * `it's`, `"scare quotes"`, a newline or an em dash survive intact.
   */
  private string(): string {
    const prefix = STRING_PREFIX.exec(this.src.slice(this.pos))?.[0] ?? "";
    this.pos += prefix.length;
    const raw = /[rR]/.test(prefix);
    const quote = this.src[this.pos];
    if (quote !== "'" && quote !== '"') this.fail("expected a quote");
    const triple = this.src.startsWith(quote.repeat(3), this.pos);
    const terminator = triple ? quote.repeat(3) : quote;
    this.pos += terminator.length;

    let out = "";
    while (true) {
      if (this.pos >= this.src.length) this.fail("unterminated string");
      if (this.src.startsWith(terminator, this.pos)) {
        this.pos += terminator.length;
        return out;
      }
      const ch = this.src[this.pos];
      if (ch !== "\\") {
        out += ch;
        this.pos++;
        continue;
      }
      if (raw) {
        // In a raw string the backslash is data; it still escapes the quote
        // for the purpose of finding the end, but both characters are kept.
        out += ch + (this.src[this.pos + 1] ?? "");
        this.pos += 2;
        continue;
      }
      out += this.escape();
    }
  }

  /** One backslash escape, positioned on the backslash. */
  private escape(): string {
    this.pos++; // the backslash
    const ch = this.src[this.pos];
    if (ch === undefined) this.fail("unterminated escape");
    this.pos++;
    if (ch === "\n") return ""; // line continuation
    const simple = SIMPLE_ESCAPES[ch];
    // `\0` is NUL only when no octal digit follows; `\012` is a form feed.
    if (simple !== undefined && !(ch === "0" && DIGITS.test(this.src[this.pos] ?? ""))) return simple;
    if (ch === "x") return this.codepoint(2, 16);
    if (ch === "u") return this.codepoint(4, 16);
    if (ch === "U") return this.codepoint(8, 16);
    if (/[0-7]/.test(ch)) {
      let digits = ch;
      while (digits.length < 3 && /[0-7]/.test(this.src[this.pos] ?? "")) digits += this.src[this.pos++];
      return String.fromCodePoint(parseInt(digits, 8));
    }
    // Python keeps an unrecognized escape verbatim, backslash included.
    return `\\${ch}`;
  }

  private codepoint(width: number, radix: number): string {
    const digits = this.src.slice(this.pos, this.pos + width);
    if (digits.length !== width || !/^[0-9a-fA-F]+$/.test(digits)) this.fail("bad character escape");
    this.pos += width;
    const code = parseInt(digits, radix);
    if (code > 0x10ffff) this.fail("character escape out of range");
    return String.fromCodePoint(code);
  }

  private number(): number {
    const rest = this.src.slice(this.pos);
    // `-inf` / `+nan` are signed keywords, not digits.
    const signed = /^[+-]\s*(inf(inity)?|nan)\b/i.exec(rest);
    if (signed) {
      this.pos += signed[0].length;
      const negative = signed[0][0] === "-";
      if (/nan/i.test(signed[0])) return Number.NaN;
      return negative ? -Infinity : Infinity;
    }
    const m = /^[+-]?(?:\d[\d_]*(?:\.[\d_]*)?|\.\d[\d_]*)(?:[eE][+-]?\d[\d_]*)?/.exec(rest);
    if (!m) this.fail("expected a number");
    // A complex literal (`1j`) or an int base prefix (`0x1f`) is not JSON data.
    if (/^[jJxXoObB_]/.test(rest.slice(m[0].length))) this.fail("unsupported numeric literal");
    this.pos += m[0].length;
    const n = Number(m[0].replace(/_/g, ""));
    if (!Number.isFinite(n) && !Number.isNaN(n)) this.fail("number out of range");
    return n;
  }

  /** `None`, `True`, `False`, `inf`, `nan` — and nothing else. */
  private keyword(): unknown {
    const m = new RegExp(`^${IDENT_START.source}${IDENT_CHAR.source}*`).exec(this.src.slice(this.pos));
    if (!m) this.fail("expected a keyword");
    const word = m[0];
    this.pos += word.length;
    switch (word) {
      case "None": return null;
      case "True": return true;
      case "False": return false;
      case "Infinity":
      case "inf": return Infinity;
      case "nan": return Number.NaN;
      default:
        // A constructor call (`ObjectId('…')`, `datetime.datetime(…)`) lands
        // here. Guessing what it meant is how a wrong value gets posted.
        this.fail(`unsupported literal "${word.slice(0, 40)}"`);
    }
  }
}

/** A dict key as an object key — Python allows numbers and tuples; JSON does not. */
function keyOf(key: unknown, reader: LiteralReader): string {
  if (typeof key === "string") return key;
  if (typeof key === "number" || typeof key === "boolean" || key === null) return String(key);
  reader.fail("unsupported dict key");
}
