"use client";

import { useCallback, useEffect, useRef, useState, type ComponentProps } from "react";
import { Check } from "lucide-react";
import { Switch } from "@/components/ui/switch";
import { Skeleton } from "@/components/ui/skeleton";
import { useFileById } from "@/lib/queries/files";
import { useUpdateAudioRights } from "@/lib/queries/audio-rights";
import { effectiveRights } from "@/lib/audio-rights/read";
import type { AudioTrack } from "@/lib/audio-rights/types";
import { SongOnSocial } from "./song-on-social";

const CLASS_LINE = { copyrighted: "Copyrighted", generated: "Generated by libi", owned: "Yours" } as const;
export const AUTOSAVE_MS = 600;
const SAVED_TICK_MS = 2_000;

/** A one-row textarea that grows with its text. */
function AutoGrowTextarea(props: ComponentProps<"textarea">) {
  const ref = useRef<HTMLTextAreaElement>(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${el.scrollHeight}px`;
  }, [props.value]);
  return (
    <textarea
      ref={ref}
      rows={1}
      {...props}
      className="w-full resize-none overflow-hidden rounded-md border border-input bg-background px-2 py-1 text-[11px] outline-none focus-visible:ring-1 focus-visible:ring-ring"
    />
  );
}

/** Title and Artist (auto-saved), the rights line with "I own this", and the
 *  song's platforms (addendum §6). */
export function AudioRightsSection({ fileId }: { fileId: string }) {
  const file = useFileById(fileId);
  const update = useUpdateAudioRights();
  const rights = file.data ? effectiveRights(file.data) : null;
  const [draft, setDraft] = useState<{ title: string; artist: string } | null>(null);
  const [saved, setSaved] = useState(false);
  const [prevFile, setPrevFile] = useState(fileId);
  if (prevFile !== fileId) {
    setPrevFile(fileId);
    setDraft(null);
  }
  const latest = useRef({ draft, rights });
  useEffect(() => {
    latest.current = { draft, rights };
  });
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const savedTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // The last {title, artist} this component actually sent: a blur landing right
  // after an autosave (before the file query refetches) must not re-send the
  // same values just because `rights.track` hasn't caught up yet.
  const lastSent = useRef<{ title: string; artist: string } | null>(null);

  const flush = useCallback(() => {
    if (timer.current) {
      clearTimeout(timer.current);
      timer.current = null;
    }
    const { draft: d, rights: r } = latest.current;
    if (!d || !r) return;
    const title = d.title.trim();
    const artist = d.artist.trim();
    // An empty title keeps the last good value.
    if (!title) return;
    if (title === (r.track?.title ?? "") && artist === (r.track?.artist ?? "")) return;
    if (lastSent.current && title === lastSent.current.title && artist === lastSent.current.artist) return;
    const sent = { title, artist };
    lastSent.current = sent;
    const { artist: _oldArtist, trackConfidence, ...kept } = r.track ?? ({} as Partial<AudioTrack>);
    void _oldArtist;
    update.mutate(
      {
        fileId,
        track: {
          ...kept,
          title,
          ...(artist ? { artist } : {}),
          // The user just confirmed the identity by editing it — a page title (yt-dlp) is no longer "low".
          ...(trackConfidence ? { trackConfidence: "high" as const } : {}),
        },
      },
      {
        // A failed save was never saved: the next blur must send it again.
        onError: () => {
          if (lastSent.current === sent) lastSent.current = null;
        },
        onSuccess: () => {
          setSaved(true);
          if (savedTimer.current) clearTimeout(savedTimer.current);
          savedTimer.current = setTimeout(() => {
            setSaved(false);
            savedTimer.current = null;
          }, SAVED_TICK_MS);
        },
      },
    );
  }, [fileId, update]);
  const flushRef = useRef(flush);
  useEffect(() => {
    flushRef.current = flush;
  });
  useEffect(() => () => {
    if (savedTimer.current) clearTimeout(savedTimer.current);
  }, []);
  // Runs on unmount AND whenever `fileId` changes: `flushRef.current` at that
  // point is still the OLD file's flush (its own ref-sync effect ran on the
  // last commit, before this one's cleanups), so a pending debounced edit is
  // saved to the file it was typed on — never to the file being switched to.
  // `lastSent` is cleared right after, so the next file starts with no dedupe
  // baggage carried over from the one just left.
  useEffect(
    () => () => {
      flushRef.current();
      lastSent.current = null;
    },
    [fileId],
  );

  const edit = (patch: Partial<{ title: string; artist: string }>) => {
    const base = draft ?? { title: rights?.track?.title ?? "", artist: rights?.track?.artist ?? "" };
    const next = { ...base, ...patch };
    setDraft(next);
    latest.current = { ...latest.current, draft: next };
    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(() => flushRef.current(), AUTOSAVE_MS);
  };

  if (file.isLoading) {
    return (
      <div className="space-y-1.5 rounded border border-border p-2" data-testid="audio-rights-section-skeleton">
        <Skeleton className="h-3 w-12" />
        <Skeleton className="h-6 w-full" />
        <Skeleton className="h-3 w-12" />
        <Skeleton className="h-6 w-full" />
        <Skeleton className="h-3 w-40" />
      </div>
    );
  }
  if (!rights) return null;
  const shown = draft ?? { title: rights.track?.title ?? "", artist: rights.track?.artist ?? "" };
  return (
    <div className="space-y-1.5 rounded border border-border p-2" data-testid="audio-rights-section">
      <label className="block space-y-0.5 text-[11px]">
        <span className="text-muted-foreground">Title</span>
        <AutoGrowTextarea data-testid="audio-rights-title" value={shown.title} onChange={(e) => edit({ title: e.target.value })} onBlur={() => flush()} />
      </label>
      <label className="block space-y-0.5 text-[11px]">
        <span className="text-muted-foreground">Artist</span>
        <AutoGrowTextarea data-testid="audio-rights-artist" value={shown.artist} onChange={(e) => edit({ artist: e.target.value })} onBlur={() => flush()} />
      </label>
      {saved && (
        <span data-testid="audio-rights-saved" className="inline-flex items-center gap-1 text-[11px] text-muted-foreground">
          <Check className="size-3" />
          Saved
        </span>
      )}
      <div className="text-[11px] text-muted-foreground" data-testid="audio-rights-line">
        {CLASS_LINE[rights.class]}
        {rights.class === "copyrighted" ? " — left out of social exports by default" : ""}
      </div>
      {rights.class !== "generated" && (
        <label className="flex cursor-pointer items-center gap-2 text-[11px]">
          <Switch
            data-testid="audio-rights-owned"
            checked={rights.class === "owned"}
            onCheckedChange={(v: boolean) => update.mutate({ fileId, class: v ? "owned" : "copyrighted" })}
            className="cursor-pointer"
          />
          I own this
        </label>
      )}
      {/* Keyed by file: an open picker or a Find again result never carries over to another file. */}
      <SongOnSocial key={fileId} fileId={fileId} rights={rights} />
      {update.error && <p className="text-[11px] text-red-500">{update.error.message}</p>}
    </div>
  );
}
